### ISSUE TITLE
Document Generation Issue - TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vedantroy** [xperiments/TSDoc#18]
When I run tsdoc, I get the following error. I can provide other files from my project if need be. 

```
PS C:\Users\vroy1\Documents\Programming\Srini\Puzzles-Webapp\puzzled\puzzled-javascript\src> tsdoc
TSDOC v0.0.4
TSDoc Generating doc...
(node:34192) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
TSDoc Done.
exec error: Error: Command failed: jsdoc /Users/vroy1/Documents/Programming/Srini/Puzzles-Webapp/puzzled/puzzled-javascript/src/ -c C:\Users\vroy1\Documents\Programming\Srini\Puzzles-Webapp\puzzled\puzzled-javascript\src\tsdoc.json -d /Users/vroy1/Documents/Programming/Srini/Puzzles-Webapp/puzzled/puzzled-javascript/src/docs
undefined:50
                                        for( var tt =0; tt< findCls.members.length; tt++ )
                                                                            ^

TypeError: Cannot read property 'length' of undefined
    at exports.Template.eval (eval at _.template (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:50:42)
    at exports.Template.template (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1461:21)
    at exports.Template.partial (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\lib\jsdoc\template.js:55:29)
    at exports.Template.render (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\lib\jsdoc\template.js:74:24)
    at generate (C:\Users\vroy1\AppData\Roaming\npm\node_modules\tsdoc\template\publish.js:274:15)
    at Object.exports.publish (C:\Users\vroy1\AppData\Roaming\npm\node_modules\tsdoc\template\publish.js:728:2)
    at Object.module.exports.cli.generateDocs (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\cli.js:448:35)
    at Object.module.exports.cli.processParseResults (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\cli.js:399:20)
    at module.exports.cli.main (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\cli.js:240:14)
    at Object.module.exports.cli.runCommand (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\cli.js:189:5)
    at C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\jsdoc.js:105:9
    at Object.<anonymous> (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\jsdoc.js:106:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by ghost** [comment]
> When I run tsdoc, I get the following error. I can provide other files from my project if need be.
> 
> ```
> PS C:\Users\vroy1\Documents\Programming\Srini\Puzzles-Webapp\puzzled\puzzled-javascript\src> tsdoc
> TSDOC v0.0.4
> TSDoc Generating doc...
> (node:34192) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
> TSDoc Done.
> exec error: Error: Command failed: jsdoc /Users/vroy1/Documents/Programming/Srini/Puzzles-Webapp/puzzled/puzzled-javascript/src/ -c C:\Users\vroy1\Documents\Programming\Srini\Puzzles-Webapp\puzzled\puzzled-javascript\src\tsdoc.json -d /Users/vroy1/Documents/Programming/Srini/Puzzles-Webapp/puzzled/puzzled-javascript/src/docs
> undefined:50
>                                         for( var tt =0; tt< findCls.members.length; tt++ )
>                                                                             ^
> 
> TypeError: Cannot read property 'length' of undefined
>     at exports.Template.eval (eval at _.template (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:50:42)
>     at exports.Template.template (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\node_modules\underscore\underscore.js:1461:21)
>     at exports.Template.partial (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\lib\jsdoc\template.js:55:29)
>     at exports.Template.render (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\lib\jsdoc\template.js:74:24)
>     at generate (C:\Users\vroy1\AppData\Roaming\npm\node_modules\tsdoc\template\publish.js:274:15)
>     at Object.exports.publish (C:\Users\vroy1\AppData\Roaming\npm\node_modules\tsdoc\template\publish.js:728:2)
>     at Object.module.exports.cli.generateDocs (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\cli.js:448:35)
>     at Object.module.exports.cli.processParseResults (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\cli.js:399:20)
>     at module.exports.cli.main (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\cli.js:240:14)
>     at Object.module.exports.cli.runCommand (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\cli.js:189:5)
>     at C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\jsdoc.js:105:9
>     at Object.<anonymous> (C:\Users\vroy1\AppData\Roaming\npm\node_modules\jsdoc\jsdoc.js:106:3)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
> ```

Same

**Comment by gh-andre** [comment]
Same here, a year later. tsdoc v0.0.4, Windows, Linux.
